# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BnM_pBfQ6bcC8Pcph2LS79VoJ-JxqxO
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

import os

os.listdir("/content")

os.listdir("/content")

import os

for f in os.listdir("/content"):
    print(f)

df.columns

df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

df = pd.read_csv("/content/dados_tratados.csv")
df.head()

df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

df["Churn"].value_counts(normalize=True)

corr = df_encoded.corr()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14,10))
sns.heatmap(corr, cmap="coolwarm", annot=False)
plt.title("Matriz de Correlação")
plt.show()

corr["Churn_Yes"].sort_values(ascending=False)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.boxplot(x=df["Churn"], y=df["customer.tenure"])
plt.title("Tempo de Contrato × Evasão")
plt.xlabel("Churn")
plt.ylabel("Tempo de Contrato (meses)")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(x=df["Churn"], y=df["account.Charges.Total"])
plt.title("Total Gasto × Evasão")
plt.xlabel("Churn")
plt.ylabel("Total Gasto")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(
    data=df,
    x="customer.tenure",
    y="account.Charges.Total",
    hue="Churn",
    alpha=0.6
)
plt.title("Dispersão: Tempo de Contrato × Total Gasto × Evasão")
plt.xlabel("Tempo de Contrato (meses)")
plt.ylabel("Total Gasto")
plt.show()

X = df_encoded.drop("Churn_Yes", axis=1)
y = df_encoded["Churn_Yes"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42
)

from sklearn.tree import DecisionTreeClassifier

modelo_dt = DecisionTreeClassifier(random_state=42)
modelo_dt.fit(X_train, y_train)

"""- Árvores de decisão fazem divisões baseadas em regras (ex.: Charges.Total > 500).
- A escala dos dados não afeta o modelo.
- Fácil de interpretar e visualizar.

"""

from sklearn.ensemble import RandomForestClassifier

modelo_rf = RandomForestClassifier(random_state=42)
modelo_rf.fit(X_train, y_train)

"""- É um conjunto de várias árvores (modelo robusto).
- Não depende de distância nem de escala.
- Geralmente tem ótimo desempenho em churn.

Foram criados dois modelos preditivos sem normalização dos dados: Decision Tree e Random Forest. A normalização não foi aplicada porque ambos os algoritmos são baseados em árvores de decisão, que realizam divisões por regras e não dependem da escala das variáveis. Dessa forma, os modelos funcionam adequadamente com os dados originais, atendendo ao objetivo de comparar diferentes abordagens de classificação para prever a evasão de clientes
"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Predições
pred_dt = modelo_dt.predict(X_test)

# Métricas
print("=== Decision Tree ===")
print("Acurácia:", accuracy_score(y_test, pred_dt))
print("Precisão:", precision_score(y_test, pred_dt))
print("Recall:", recall_score(y_test, pred_dt))
print("F1-score:", f1_score(y_test, pred_dt))
print("\nRelatório de Classificação:\n", classification_report(y_test, pred_dt))

# Matriz de confusão
cm_dt = confusion_matrix(y_test, pred_dt)

plt.figure(figsize=(6,4))
sns.heatmap(cm_dt, annot=True, fmt="d", cmap="Blues")
plt.title("Matriz de Confusão - Decision Tree")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

# Predições
pred_rf = modelo_rf.predict(X_test)

# Métricas
print("=== Random Forest ===")
print("Acurácia:", accuracy_score(y_test, pred_rf))
print("Precisão:", precision_score(y_test, pred_rf))
print("Recall:", recall_score(y_test, pred_rf))
print("F1-score:", f1_score(y_test, pred_rf))
print("\nRelatório de Classificação:\n", classification_report(y_test, pred_rf))

# Matriz de confusão
cm_rf = confusion_matrix(y_test, pred_rf)

plt.figure(figsize=(6,4))
sns.heatmap(cm_rf, annot=True, fmt="d", cmap="Greens")
plt.title("Matriz de Confusão - Random Forest")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

"""Entre os dois modelos testados, o Random Forest foi o que apresentou o melhor desempenho geral. Ele conseguiu métricas mais equilibradas e mostrou maior capacidade de identificar corretamente os clientes que realmente evadem. Isso acontece porque ele combina várias árvores e, com isso, consegue aprender os padrões dos dados sem perder a capacidade de generalizar.
A Decision Tree, por outro lado, apresentou sinais claros de overfitting. Ela se ajustou demais aos dados de treino e, por isso, teve um desempenho inferior quando aplicada ao conjunto de teste. Esse comportamento é comum em árvores individuais, que podem ficar complexas demais e acabar “decorando” os dados em vez de aprender padrões mais amplos.
Nenhum dos modelos mostrou underfitting, já que ambos conseguiram aprender tendências importantes da base. A diferença é que o Random Forest conseguiu equilibrar melhor aprendizado e generalização, enquanto a Decision Tree precisaria de ajustes — como limitar a profundidade da árvore — para evitar o excesso de complexidade.

A análise das variáveis mais importantes no modelo Random Forest mostrou que algumas características dos clientes têm maior influência na previsão de evasão. O tempo de contrato e o total gasto aparecem como fatores centrais, já que clientes mais novos tendem a cancelar com mais frequência. O tipo de contrato também se destacou, especialmente os contratos mensais, que apresentam maior instabilidade. Além disso, variáveis relacionadas aos serviços contratados e ao método de pagamento contribuíram para diferenciar perfis com maior risco de churn. Essas informações ajudam a entender melhor o comportamento dos clientes e mostram quais fatores merecem mais atenção em estratégias de retenção.

A análise mostrou que o Random Forest teve o melhor desempenho e ajudou a identificar os fatores que mais influenciam a evasão. As variáveis mais importantes foram o tempo de contrato, o total gasto, o tipo de contrato e alguns serviços contratados. Clientes novos, com pouco histórico e contratos mensais apresentaram maior risco de cancelamento. A Decision Tree mostrou sinais de overfitting, enquanto o Random Forest generalizou melhor. Com base nesses resultados, estratégias de retenção podem focar em acompanhar clientes nos primeiros meses, incentivar contratos mais longos e ajustar serviços que geram insatisfação. Essas ações ajudam a reduzir a evasão e fortalecer o relacionamento com o cliente.
"""